import { ClientProvider } from '@/components/ClientProvider';
import './global.css';
import { Google_Sans_Flex } from 'next/font/google';

const googleSansFlex = Google_Sans_Flex({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-google-sans-flex',
  adjustFontFallback: true,
});

export const metadata = {
  title: 'Welcome to Edu-Flow',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${googleSansFlex.variable}`}>
        <ClientProvider>
          {children}
        </ClientProvider>
      </body>
    </html>
  )
}
