import { ClientProvider } from '@/components/ClientProvider';
import './global.css';

export const metadata = {
  title: 'Welcome to Edu-Flow',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          {children}
        </ClientProvider>
      </body>
    </html>
  )
}
